services:
  tm_client:
    build: .
    depends_on:
      tm_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - tm-net
    ports:
      - '80:3000'

  tm_db:
    image: mongo:latest
    networks:
      - tm-net
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/var/lib/mongo
    healthcheck:
      test: mongo -h
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mongo-data:

networks:
  tm-net:
